version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: medicore-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=medicore_root_pass
      - MYSQL_DATABASE=medicore
      - MYSQL_USER=medicore_user
      - MYSQL_PASSWORD=medicore_pass
    ports:
      - "3306:3306"
    volumes:
      - ./backend/MediCore/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medicore-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: medicore-phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=medicore_root_pass
    ports:
      - "8081:80"
    networks:
      - medicore-net

networks:
  medicore-net:
    driver: bridge
